import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useEffect,useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';


export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  const [backgroundImage, setBackgroundImage] = useState('');
  useEffect(() => {
    // Set default background image
    setBackgroundImage(getBackgroundImage('Default'));
  }, []);
  
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      setBackgroundImage(getBackgroundImage(response.data.weather[0].main));
    });
    setCity('');
    setLoading(false);
  };

  const getBackgroundImage = (weatherCondition) => {
    switch (weatherCondition) {
      case 'Clear':
        return 'https://images.unsplash.com/photo-1531386450450-969f935bd522?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2xlYXIlMjAlMjBuYXR1cmUlMjBiYWNrZ3JvdW5kfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60';
      case 'Clouds':
        return 'https://images.unsplash.com/photo-1603288967520-f3e04381dc02?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80'; 
      case 'Rain':
        return 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80'; 
      
      default:
        return 'https://images.unsplash.com/photo-1650980331974-b6268d3be45f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80'; 
    }
  };
  
 

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Mary Rainy Poppins</title>
          <meta name='description' content='Generated by create next app' />
          
        <link rel='icon' href='/kklogo2.jpg' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        
        </Head>
        



        <div className='left-0 right-0 bottom-0 absolute top-0  bg-black/60 z-[1]' />
                {/* bg image */}
        <Image
           src={backgroundImage}
          layout='fill'
          className='object-cover'
        />

        {/* Search */}
        
        
            
            <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
          
          <form
                    onSubmit={fetchWeather}
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'
          >
            <div>
              <input
                  onChange={(e) => setCity(e.target.value)}
                  className='bg-transparent border-none text-white focus:outline-none text-3xl'
                  type='text'
                  placeholder='Search city'
              />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={18} />
                      </button>
            </form>

        </div>

        {/* Weather */}
        {weather.main && <Weather data={weather} />}
      </div>
    );
  }
}
